name: CI
on:
   push:
      branches:   [ "main" ]
   pull_request:
      branches:   [ "main" ]
jobs:
  build:
     permissions: write-all
     runs-on: self-hosted
     steps:
      - uses: actions/checkout@v3
      - name: OWASP ZAP baseline
        uses: zaproxy/action-baseline@v0.7.0
        with:
            target: "https://www.zaproxy.org"
