name: CI
on:
   push:
     branches:["main"]
   pull_request:
     branches:["main"]
jobs:
  build:
     runs-on:unbantu-latest
      
  steps:
    - uses: actions/checkout@v3
    - name: OWASP ZAP baseline
      uses: zapproxy/action-baseline@v0.7.0
      with:
        target: "https://dotnetthoughts.net"
